-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 22:46:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre_municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localidades` (
  `idlocalidades` INT NOT NULL AUTO_INCREMENT,
  `nombre_localidad` VARCHAR(45) NOT NULL,
  `ambito` CHAR(1) NOT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idlocalidades`, `municipio_idmunicipio`),
  INDEX `fk_localidades_municipio1_idx` (`municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_localidades_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `mydb`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vivienda` (
  `idvivienda` INT NOT NULL AUTO_INCREMENT,
  `tipo_vivienda` VARCHAR(20) NOT NULL,
  `material` VARCHAR(20) NOT NULL,
  `saneamiento` VARCHAR(20) NOT NULL,
  `agua` CHAR(2) NOT NULL,
  `luz` CHAR(2) NOT NULL,
  `drenaje` CHAR(2) NOT NULL,
  `tendencia` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `num_habitaciones` INT NOT NULL,
  `num_banios` INT NOT NULL,
  `localidades_idlocalidades` INT NOT NULL,
  `localidades_municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idvivienda`, `localidades_idlocalidades`, `localidades_municipio_idmunicipio`),
  INDEX `fk_vivienda_localidades1_idx` (`localidades_idlocalidades` ASC, `localidades_municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_vivienda_localidades1`
    FOREIGN KEY (`localidades_idlocalidades` , `localidades_municipio_idmunicipio`)
    REFERENCES `mydb`.`localidades` (`idlocalidades` , `municipio_idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habitante` (
  `idhabitante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `edo_civil` VARCHAR(20) NOT NULL,
  `nivel_educativo` VARCHAR(20) NOT NULL,
  `ingresos` INT NOT NULL,
  `nacionalidad` VARCHAR(20) NOT NULL,
  `vivienda_idvivienda` INT NOT NULL,
  PRIMARY KEY (`idhabitante`, `vivienda_idvivienda`),
  INDEX `fk_habitante_vivienda1_idx` (`vivienda_idvivienda` ASC) VISIBLE,
  CONSTRAINT `fk_habitante_vivienda1`
    FOREIGN KEY (`vivienda_idvivienda`)
    REFERENCES `mydb`.`vivienda` (`idvivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ocupacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ocupacion` (
  `idocupacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_ocupacion` VARCHAR(20) NOT NULL,
  `detalle_ocupacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idocupacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login_usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `pass` BLOB NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habitante_ocupacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habitante_ocupacion` (
  `habitante_idhabitante` INT NOT NULL,
  `ocupacion_idocupacion` INT NOT NULL,
  PRIMARY KEY (`habitante_idhabitante`, `ocupacion_idocupacion`),
  INDEX `fk_habitante_ocupacion_ocupacion1_idx` (`ocupacion_idocupacion` ASC) VISIBLE,
  CONSTRAINT `fk_habitante_ocupacion_habitante1`
    FOREIGN KEY (`habitante_idhabitante`)
    REFERENCES `mydb`.`habitante` (`idhabitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitante_ocupacion_ocupacion1`
    FOREIGN KEY (`ocupacion_idocupacion`)
    REFERENCES `mydb`.`ocupacion` (`idocupacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
